#!/usr/bin/env python3
"""
ComplianceYieldTreasury MCP Server
===================================
Synthesis Hackathon 2026 — Lido Finance $5,000 bounty (MCP server track)

This MCP server exposes the ComplianceYieldTreasury contract as natural-language
tools that any AI agent can use to stake wstETH, harvest yield, and monitor
positions — without the agent ever needing to understand raw Solidity or ABI encoding.

Usage:
    python server.py

Connect in Claude/any MCP client:
    mcp install server.py

Tools exposed:
    - stake_wsteth        : Stake wstETH into the compliance-gated treasury
    - harvest_yield       : Withdraw accrued yield to spending wallet
    - get_position        : Get full position details for an agent
    - check_eligibility   : Check if an agent is eligible to stake
    - get_treasury_stats  : Get overall treasury statistics
    - register_erc8004    : Register agent in ERC-8004 identity registry
    - monitor_vault       : Get vault health report in plain English
"""

import os
import json
import time
from typing import Optional
from fastmcp import FastMCP
from web3 import Web3
from eth_account import Account
from dotenv import load_dotenv

load_dotenv()

# ─── Configuration ───────────────────────────────────────────────────────────

BASE_RPC = os.getenv("BASE_RPC_URL", "https://mainnet.base.org")
PRIVATE_KEY = os.getenv("PRIVATE_KEY")  # Deployer/operator private key
TREASURY_ADDRESS = os.getenv("TREASURY_ADDRESS")  # Set after deployment
LOCUS_WALLET = os.getenv("LOCUS_WALLET", "0xCb99E647AAb7670eb08947126C8525285A965AD7")

# Base mainnet addresses (hardcoded — verified onchain)
WSTETH_ADDRESS = "0xc1CBa3fCea344f92D9239c08C0568f6F2F0ee452"
AWSTETH_ADDRESS = "0x99CBC45ea5bb7eF3a5BC08FB1B7E56bB2442Ef0D"
AAVE_POOL_ADDRESS = "0xA238Dd80C259a72e81d7e4664a9801593F98d1c5"
AGENT_REGISTRY_ADDRESS = "0x8004A169FB4a3325136EB29fA0ceB6D2e539a432"
REPUTATION_REGISTRY_ADDRESS = "0x8004BAa17C55a88189AE136b182e5fdA19dE9b63"

# ─── Web3 Setup ──────────────────────────────────────────────────────────────

w3 = Web3(Web3.HTTPProvider(BASE_RPC))

# Load contract ABIs (generated by `forge build`)
def load_abi(contract_name: str) -> list:
    abi_path = f"../compliance-yield-treasury/out/{contract_name}.sol/{contract_name}.json"
    try:
        with open(abi_path) as f:
            return json.load(f)["abi"]
    except FileNotFoundError:
        return []

TREASURY_ABI = load_abi("ComplianceYieldTreasury")

ERC20_ABI = [
    {"inputs": [{"name": "account", "type": "address"}], "name": "balanceOf", "outputs": [{"name": "", "type": "uint256"}], "type": "function", "stateMutability": "view"},
    {"inputs": [{"name": "spender", "type": "address"}, {"name": "amount", "type": "uint256"}], "name": "approve", "outputs": [{"name": "", "type": "bool"}], "type": "function", "stateMutability": "nonpayable"},
    {"inputs": [], "name": "decimals", "outputs": [{"name": "", "type": "uint8"}], "type": "function", "stateMutability": "view"},
    {"inputs": [], "name": "symbol", "outputs": [{"name": "", "type": "string"}], "type": "function", "stateMutability": "view"},
]

AGENT_REGISTRY_ABI = [
    {"inputs": [{"name": "agentURI", "type": "string"}, {"name": "metadata", "type": "bytes"}], "name": "register", "outputs": [{"name": "", "type": "uint256"}], "type": "function", "stateMutability": "nonpayable"},
    {"inputs": [{"name": "tokenId", "type": "uint256"}], "name": "ownerOf", "outputs": [{"name": "", "type": "address"}], "type": "function", "stateMutability": "view"},
    {"inputs": [{"name": "tokenId", "type": "uint256"}], "name": "tokenURI", "outputs": [{"name": "", "type": "string"}], "type": "function", "stateMutability": "view"},
    {"inputs": [{"name": "owner", "type": "address"}], "name": "balanceOf", "outputs": [{"name": "", "type": "uint256"}], "type": "function", "stateMutability": "view"},
    {"inputs": [], "name": "name", "outputs": [{"name": "", "type": "string"}], "type": "function", "stateMutability": "view"},
]

# ─── Helper Functions ─────────────────────────────────────────────────────────

def get_treasury_contract():
    if not TREASURY_ADDRESS:
        raise ValueError("TREASURY_ADDRESS not set. Deploy the contract first.")
    return w3.eth.contract(address=Web3.to_checksum_address(TREASURY_ADDRESS), abi=TREASURY_ABI)

def get_account():
    if not PRIVATE_KEY:
        raise ValueError("PRIVATE_KEY not set in environment.")
    return Account.from_key(PRIVATE_KEY)

def wei_to_eth(wei: int, decimals: int = 18) -> float:
    return wei / (10 ** decimals)

def format_address(addr: str) -> str:
    """Format address with 0x prefix and checksum."""
    return Web3.to_checksum_address(addr)

def send_transaction(tx_data: dict) -> dict:
    """Sign and broadcast a transaction."""
    account = get_account()
    tx_data["from"] = account.address
    tx_data["nonce"] = w3.eth.get_transaction_count(account.address)
    tx_data["gasPrice"] = w3.eth.gas_price
    
    if "gas" not in tx_data:
        tx_data["gas"] = w3.eth.estimate_gas(tx_data)
    
    signed = account.sign_transaction(tx_data)
    tx_hash = w3.eth.send_raw_transaction(signed.raw_transaction)
    receipt = w3.eth.wait_for_transaction_receipt(tx_hash, timeout=120)
    
    return {
        "tx_hash": tx_hash.hex(),
        "block_number": receipt["blockNumber"],
        "gas_used": receipt["gasUsed"],
        "status": "success" if receipt["status"] == 1 else "reverted",
        "basescan_url": f"https://basescan.org/tx/0x{tx_hash.hex()}"
    }

# ─── MCP Server ──────────────────────────────────────────────────────────────

mcp = FastMCP(
    "ComplianceYieldTreasury",
    description="""
    ERC-3643 Compliant Yield Treasury for AI Agents — Synthesis Hackathon 2026
    
    This server lets AI agents stake wstETH (Lido's wrapped staked ETH) into a 
    compliance-gated treasury on Base. The principal is structurally locked and 
    only yield flows to the agent's spending wallet.
    
    Built for: Lido Finance + Locus + Protocol Labs ERC-8004 bounties.
    """
)

# ─── Tool 1: Check Eligibility ───────────────────────────────────────────────

@mcp.tool()
def check_eligibility(agent_address: str, erc8004_agent_id: int) -> dict:
    """
    Check if an AI agent is eligible to stake in the compliance treasury.
    
    Verifies:
    1. ERC-3643 compliance status (KYC/identity verification)
    2. ERC-8004 agent identity ownership
    
    Args:
        agent_address: The agent's Ethereum address
        erc8004_agent_id: The agent's ERC-8004 identity token ID
    
    Returns:
        Eligibility status with reasons
    """
    try:
        treasury = get_treasury_contract()
        agent_addr = format_address(agent_address)
        
        erc3643_ok, erc8004_ok, eligible = treasury.functions.isEligible(
            agent_addr, erc8004_agent_id
        ).call()
        
        result = {
            "agent_address": agent_addr,
            "erc8004_agent_id": erc8004_agent_id,
            "erc3643_compliant": erc3643_ok,
            "erc8004_identity_valid": erc8004_ok,
            "eligible_to_stake": eligible,
            "explanation": []
        }
        
        if not erc3643_ok:
            result["explanation"].append("Agent not verified in ERC-3643 identity registry. Needs KYC/compliance verification.")
        if not erc8004_ok:
            result["explanation"].append(f"Agent does not own ERC-8004 token ID {erc8004_agent_id}. Register at ERC-8004 registry first.")
        if eligible:
            result["explanation"].append("✅ Agent is fully compliant and eligible to stake.")
            
        return result
    except Exception as e:
        return {"error": str(e), "eligible_to_stake": False}

# ─── Tool 2: Get Position ─────────────────────────────────────────────────────

@mcp.tool()
def get_position(agent_address: str) -> dict:
    """
    Get the full staking position for an agent.
    
    Shows: principal locked, current Aave balance, accrued yield,
    spending wallet, ERC-8004 agent ID, and total yield harvested.
    
    Args:
        agent_address: The agent's Ethereum address
    
    Returns:
        Complete position details with yield estimates in human-readable format
    """
    try:
        treasury = get_treasury_contract()
        agent_addr = format_address(agent_address)
        
        (
            principal_wsteth,
            current_awsteth,
            estimated_yield,
            spending_wallet,
            erc8004_id,
            total_yield_harvested,
            staked_at,
            active
        ) = treasury.functions.getPosition(agent_addr).call()
        
        # Get current wstETH/stETH exchange rate for context
        wsteth = w3.eth.contract(address=format_address(WSTETH_ADDRESS), abi=ERC20_ABI)
        
        result = {
            "agent_address": agent_addr,
            "active": active,
            "principal_locked": {
                "wei": principal_wsteth,
                "wstETH": f"{wei_to_eth(principal_wsteth):.6f} wstETH",
                "note": "Structurally locked — cannot be directly withdrawn by agent"
            },
            "current_aave_balance": {
                "wei": current_awsteth,
                "aWSTETH": f"{wei_to_eth(current_awsteth):.6f} aWSTETH"
            },
            "accrued_yield": {
                "wei": estimated_yield,
                "wstETH": f"{wei_to_eth(estimated_yield):.8f} wstETH",
                "available_to_harvest": estimated_yield > 0
            },
            "spending_wallet": spending_wallet,
            "erc8004_agent_id": erc8004_id,
            "total_yield_harvested": {
                "wei": total_yield_harvested,
                "wstETH": f"{wei_to_eth(total_yield_harvested):.8f} wstETH"
            },
            "staked_at": staked_at,
            "staked_at_human": time.strftime('%Y-%m-%d %H:%M UTC', time.gmtime(staked_at)) if staked_at > 0 else "Not staked"
        }
        
        return result
    except Exception as e:
        return {"error": str(e)}

# ─── Tool 3: Stake wstETH ─────────────────────────────────────────────────────

@mcp.tool()
def stake_wsteth(
    amount_wsteth: float,
    erc8004_agent_id: int,
    spending_wallet: Optional[str] = None
) -> dict:
    """
    Stake wstETH into the compliance-gated yield treasury.
    
    The principal is locked in Aave v3 on Base — earning yield continuously.
    Only the accrued yield flows to the spending wallet (default: Locus wallet).
    
    Prerequisites:
    - Agent must be ERC-3643 verified
    - Agent must own the specified ERC-8004 identity token
    - Agent must have approved the treasury contract to spend their wstETH
    
    Args:
        amount_wsteth: Amount of wstETH to stake (e.g., 0.1 for 0.1 wstETH)
        erc8004_agent_id: The agent's ERC-8004 identity token ID
        spending_wallet: Optional. Where yield will be sent. Defaults to Locus wallet.
    
    Returns:
        Transaction hash and position details
    """
    try:
        account = get_account()
        treasury = get_treasury_contract()
        
        # Convert to wei
        amount_wei = int(amount_wsteth * 10**18)
        target_wallet = format_address(spending_wallet or LOCUS_WALLET)
        
        # Step 1: Approve treasury to spend wstETH
        wsteth = w3.eth.contract(address=format_address(WSTETH_ADDRESS), abi=ERC20_ABI)
        
        approve_tx = wsteth.functions.approve(
            format_address(TREASURY_ADDRESS), amount_wei
        ).build_transaction({
            "chainId": 8453,  # Base mainnet
        })
        approve_result = send_transaction(approve_tx)
        
        if approve_result["status"] != "success":
            return {"error": "Approval transaction failed", "details": approve_result}
        
        # Step 2: Stake
        stake_tx = treasury.functions.stake(
            amount_wei,
            erc8004_agent_id,
            target_wallet
        ).build_transaction({
            "chainId": 8453,
        })
        stake_result = send_transaction(stake_tx)
        
        return {
            "status": "staked" if stake_result["status"] == "success" else "failed",
            "amount_staked": f"{amount_wsteth} wstETH",
            "spending_wallet": target_wallet,
            "erc8004_agent_id": erc8004_agent_id,
            "approve_tx": approve_result["basescan_url"],
            "stake_tx": stake_result["basescan_url"],
            "tx_hash": stake_result["tx_hash"],
            "note": "Principal is now locked. Yield will accrue to your spending wallet."
        }
    except Exception as e:
        return {"error": str(e)}

# ─── Tool 4: Harvest Yield ────────────────────────────────────────────────────

@mcp.tool()
def harvest_yield() -> dict:
    """
    Harvest accrued yield and send it to the agent's spending wallet.
    
    Only the yield (above the locked principal) is withdrawn.
    The principal remains in Aave, continuing to earn interest.
    
    Returns:
        Amount harvested and transaction details
    """
    try:
        treasury = get_treasury_contract()
        account = get_account()
        
        # Check current position first
        position = get_position(account.address)
        if "error" in position:
            return position
        
        if not position["active"]:
            return {"error": "No active staking position. Stake first."}
        
        yield_wei = position["accrued_yield"]["wei"]
        if yield_wei == 0:
            return {
                "status": "no_yield",
                "message": "No yield available to harvest yet. Position may be too new.",
                "staked_at": position["staked_at_human"]
            }
        
        # Execute harvest
        harvest_tx = treasury.functions.harvestYield().build_transaction({
            "chainId": 8453,
        })
        result = send_transaction(harvest_tx)
        
        return {
            "status": result["status"],
            "yield_harvested": position["accrued_yield"]["wstETH"],
            "sent_to": position["spending_wallet"],
            "tx_hash": result["tx_hash"],
            "basescan_url": result["basescan_url"],
            "principal_still_locked": position["principal_locked"]["wstETH"]
        }
    except Exception as e:
        return {"error": str(e)}

# ─── Tool 5: Register ERC-8004 Identity ──────────────────────────────────────

@mcp.tool()
def register_erc8004_agent(
    agent_name: str,
    agent_description: str,
    agent_endpoint: Optional[str] = None
) -> dict:
    """
    Register this agent in the ERC-8004 onchain Agent Identity Registry on Base.
    
    Creates a permanent onchain identity (NFT) for the agent at:
    0x8004A169FB4a3325136EB29fA0ceB6D2e539a432
    
    The agent ID returned is required for staking in the compliance treasury.
    
    Args:
        agent_name: Human-readable name for this agent
        agent_description: What this agent does
        agent_endpoint: Optional API endpoint for this agent
    
    Returns:
        The ERC-8004 agent token ID and transaction details
    """
    try:
        account = get_account()
        registry = w3.eth.contract(
            address=format_address(AGENT_REGISTRY_ADDRESS),
            abi=AGENT_REGISTRY_ABI
        )
        
        # Build ERC-8004 registration JSON
        registration = {
            "type": "https://eips.ethereum.org/EIPS/eip-8004#registration-v1",
            "name": agent_name,
            "description": agent_description,
            "services": [],
            "x402Support": True,
            "active": True,
            "supportedTrust": ["reputation", "tee-attestation"],
            "hackathon": "Synthesis 2026",
            "project": "ComplianceYieldTreasury"
        }
        
        if agent_endpoint:
            registration["services"].append({
                "name": "A2A",
                "endpoint": agent_endpoint,
                "version": "0.3.0"
            })
        
        # For production: upload to IPFS and use the CID as agentURI
        # For hackathon: use a data URI
        agent_uri = f"data:application/json;base64," + __import__('base64').b64encode(
            json.dumps(registration).encode()
        ).decode()
        
        metadata = __import__('eth_abi').encode(['string', 'string'], [agent_name, agent_description])
        
        tx = registry.functions.register(agent_uri, metadata).build_transaction({
            "chainId": 8453,
        })
        result = send_transaction(tx)
        
        # Get the agent ID from the transaction logs
        receipt = w3.eth.get_transaction_receipt(bytes.fromhex(result["tx_hash"]))
        # ERC-721 Transfer event — tokenId is the 3rd topic
        agent_id = None
        for log in receipt["logs"]:
            if len(log["topics"]) == 4:
                agent_id = int(log["topics"][3].hex(), 16)
                break
        
        return {
            "status": result["status"],
            "erc8004_agent_id": agent_id,
            "agent_name": agent_name,
            "owner": account.address,
            "registry": AGENT_REGISTRY_ADDRESS,
            "tx_hash": result["tx_hash"],
            "basescan_url": result["basescan_url"],
            "note": f"Save your agent ID: {agent_id}. You need it to stake in ComplianceYieldTreasury."
        }
    except Exception as e:
        return {"error": str(e)}

# ─── Tool 6: Treasury Stats ───────────────────────────────────────────────────

@mcp.tool()
def get_treasury_stats() -> dict:
    """
    Get overall treasury statistics — for the monitoring agent and dashboards.
    
    Returns:
        Total principal locked, total Aave balance, number of agents,
        estimated APY, and treasury health status.
    """
    try:
        treasury = get_treasury_contract()
        
        total_principal = treasury.functions.totalPrincipalLocked().call()
        total_aave = treasury.functions.totalAaveBalance().call()
        agent_count = treasury.functions.getAgentCount().call()
        
        # Calculate rough APY from Aave's current rate
        # liquidityRate from getReserveData is in ray (1e27)
        aave = w3.eth.contract(address=format_address(AAVE_POOL_ADDRESS), abi=[
            {"inputs": [{"name": "asset", "type": "address"}], "name": "getReserveData",
             "outputs": [
                 {"name": "configuration", "type": "uint256"},
                 {"name": "liquidityIndex", "type": "uint128"},
                 {"name": "currentLiquidityRate", "type": "uint128"},
                 {"name": "variableBorrowIndex", "type": "uint128"},
                 {"name": "currentVariableBorrowRate", "type": "uint128"},
                 {"name": "currentStableBorrowRate", "type": "uint128"},
                 {"name": "lastUpdateTimestamp", "type": "uint40"},
                 {"name": "id", "type": "uint16"},
                 {"name": "aTokenAddress", "type": "address"},
                 {"name": "stableDebtTokenAddress", "type": "address"},
                 {"name": "variableDebtTokenAddress", "type": "address"},
                 {"name": "interestRateStrategyAddress", "type": "address"},
                 {"name": "accruedToTreasury", "type": "uint128"},
                 {"name": "unbacked", "type": "uint128"},
                 {"name": "isolationModeTotalDebt", "type": "uint128"}
             ],
             "type": "function", "stateMutability": "view"}
        ])
        
        reserve_data = aave.functions.getReserveData(
            format_address(WSTETH_ADDRESS)
        ).call()
        
        # liquidityRate is in ray (1e27) — convert to APY %
        liquidity_rate_ray = reserve_data[2]
        apy = (liquidity_rate_ray / 1e27) * 100
        
        total_yield_accrued = max(0, total_aave - total_principal)
        
        return {
            "treasury_address": TREASURY_ADDRESS,
            "total_principal_locked": {
                "wei": total_principal,
                "wstETH": f"{wei_to_eth(total_principal):.6f} wstETH"
            },
            "total_aave_balance": {
                "wei": total_aave,
                "aWSTETH": f"{wei_to_eth(total_aave):.6f} aWSTETH"
            },
            "total_yield_accrued": {
                "wei": total_yield_accrued,
                "wstETH": f"{wei_to_eth(total_yield_accrued):.8f} wstETH"
            },
            "active_agents": agent_count,
            "current_apy": f"{apy:.4f}%",
            "yield_source": "Aave v3 on Base (wstETH lending)",
            "principal_lock": "STRUCTURAL — no agent can withdraw principal",
            "health": "🟢 Healthy" if total_aave >= total_principal else "🔴 Check required",
            "chain": "Base (chainId: 8453)",
            "block": w3.eth.block_number
        }
    except Exception as e:
        return {"error": str(e)}

# ─── Tool 7: Monitor Vault ────────────────────────────────────────────────────

@mcp.tool()
def monitor_vault(agent_address: Optional[str] = None) -> str:
    """
    Get a plain-English vault health report — for the Lido monitoring agent bounty.
    
    Reads all positions and explains what's happening in the vault in simple terms.
    This is what a human investor would want to hear on their morning briefing.
    
    Args:
        agent_address: Optional. If provided, focus report on this agent's position.
    
    Returns:
        A plain-English health report of the treasury vault
    """
    try:
        treasury = get_treasury_contract()
        stats = get_treasury_stats()
        
        lines = [
            "═══════════════════════════════════════════",
            "  ComplianceYieldTreasury — Vault Report",
            "═══════════════════════════════════════════",
            f"  Chain: Base (chainId 8453)",
            f"  Block: {stats.get('block', 'N/A')}",
            "",
            "  TREASURY OVERVIEW",
            f"  ├─ Total principal locked: {stats['total_principal_locked']['wstETH']}",
            f"  ├─ Current Aave balance:   {stats['total_aave_balance']['aWSTETH']}",
            f"  ├─ Accrued yield:          {stats['total_yield_accrued']['wstETH']}",
            f"  ├─ Active agents:          {stats['active_agents']}",
            f"  ├─ Current APY:            {stats['current_apy']}",
            f"  └─ Health status:          {stats['health']}",
            "",
            "  MECHANISM",
            "  ├─ Agents stake wstETH (Lido wrapped staked ETH)",
            "  ├─ wstETH is supplied to Aave v3 on Base",
            "  ├─ Only yield flows to agent spending wallets",
            "  ├─ Principal is structurally locked at contract level",
            "  └─ Agents authorized via ERC-3643 + ERC-8004 checks",
        ]
        
        if agent_address:
            pos = get_position(agent_address)
            if "error" not in pos and pos.get("active"):
                lines.extend([
                    "",
                    f"  AGENT POSITION: {agent_address[:10]}...{agent_address[-6:]}",
                    f"  ├─ Principal locked: {pos['principal_locked']['wstETH']}",
                    f"  ├─ Aave balance:     {pos['current_aave_balance']['aWSTETH']}",
                    f"  ├─ Accrued yield:    {pos['accrued_yield']['wstETH']}",
                    f"  ├─ Spending wallet:  {pos['spending_wallet'][:10]}... (Locus)",
                    f"  ├─ ERC-8004 ID:      #{pos['erc8004_agent_id']}",
                    f"  ├─ Staked at:        {pos['staked_at_human']}",
                    f"  └─ Total harvested:  {pos['total_yield_harvested']['wstETH']}",
                ])
        
        lines.extend([
            "",
            "═══════════════════════════════════════════",
        ])
        
        return "\n".join(lines)
    except Exception as e:
        return f"Monitor error: {str(e)}"

# ─── Run ──────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    print("🚀 ComplianceYieldTreasury MCP Server")
    print(f"   Base RPC: {BASE_RPC}")
    print(f"   Treasury: {TREASURY_ADDRESS or 'NOT SET — deploy first'}")
    print(f"   Locus Wallet: {LOCUS_WALLET}")
    print("")
    mcp.run()
