// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {IIdentityRegistry, ICompliance} from "./interfaces/IERC3643.sol";
import {IAgentIdentityRegistry} from "./interfaces/IERC8004.sol";
import {IERC20, IAavePool} from "./interfaces/IDefi.sol";

/**
 * @title ComplianceYieldTreasury
 * @author Alhassan Mohammed — Synthesis Hackathon 2026
 *
 * @notice An ERC-3643 compliance-gated yield treasury for AI agents.
 *
 * Design principles:
 * - Only compliance-verified agents (per ERC-3643 identity registry) can stake
 * - Agent identity is verified onchain via ERC-8004 identity registry
 * - Staked principal is STRUCTURALLY LOCKED — agents can never withdraw principal directly
 * - Only accrued yield flows to the agent's spending wallet (e.g. Locus-controlled)
 * - Yield is generated by supplying wstETH to Aave v3 on Base
 * - Built for The Synthesis Hackathon — Lido + Locus + Protocol Labs ERC-8004 tracks
 *
 * Architecture:
 *
 *   Agent (ERC-8004 verified identity)
 *     → ComplianceYieldTreasury.stake(amount)
 *         → ERC-3643 identity check (is this agent KYC'd / compliant?)
 *         → ERC-8004 agent check (is this a registered AI agent?)
 *         → wstETH deposited into Aave v3 → earns yield (aWSTETH accumulates)
 *
 *   Agent → harvestYield(agentId)
 *         → Calculate: current aWSTETH balance - principal deposited
 *         → Transfer ONLY yield to agent's Locus spending wallet
 *         → Principal remains locked in Aave forever (or until owner migration)
 *
 * Bounty coverage:
 * - Lido Finance $3,000  — treasury primitive (this contract)
 * - Lido Finance $5,000  — MCP server wrapping this contract (mcp-server/)
 * - Lido Finance $1,500  — monitoring agent (scripts/monitor.py)
 * - Locus $3,000         — Locus wallet is the yield recipient; spending guardrails applied
 * - Protocol Labs $4,000 — ERC-8004 agent identity + ERC-3643 trust layer
 */
contract ComplianceYieldTreasury {
    // ═══════════════════════════════════════════════════════════
    // CONSTANTS — Base mainnet
    // ═══════════════════════════════════════════════════════════

    /// @dev wstETH on Base (bridged from Ethereum mainnet)
    address public constant WSTETH = 0xc1CBa3fCea344f92D9239c08C0568f6F2F0ee452;

    /// @dev Aave v3 Pool on Base
    address public constant AAVE_POOL = 0xA238Dd80C259a72e81d7e4664a9801593F98d1c5;

    /// @dev aWSTETH receipt token on Base (yield-bearing)
    address public constant AWSTETH = 0x99CBC45ea5bb7eF3a5BC08FB1B7E56bB2442Ef0D;

    /// @dev ERC-8004 Agent Identity Registry (same address on 20+ chains)
    address public constant AGENT_REGISTRY = 0x8004A169FB4a3325136EB29fA0ceB6D2e539a432;

    /// @dev ERC-8004 Reputation Registry
    address public constant REPUTATION_REGISTRY = 0x8004BAa17C55a88189AE136b182e5fdA19dE9b63;

    // ═══════════════════════════════════════════════════════════
    // STATE
    // ═══════════════════════════════════════════════════════════

    address public immutable owner;

    /// @notice ERC-3643 Identity Registry for compliance checking
    address public identityRegistry;

    struct AgentPosition {
        uint256 principalWstETH;    // Amount of wstETH staked (locked forever)
        uint256 aaveShares;          // aWSTETH shares held in Aave (principal snapshot)
        address spendingWallet;      // Locus-controlled spending wallet for yield
        uint256 erc8004AgentId;      // ERC-8004 onchain agent identity token ID
        uint256 totalYieldHarvested; // Cumulative yield harvested (wei)
        uint256 stakedAt;            // Timestamp of initial stake
        bool active;                 // Position is active
    }

    /// @notice Agent address → position
    mapping(address => AgentPosition) public positions;

    /// @notice All agent addresses that have staked
    address[] public agents;

    /// @notice Total wstETH principal locked in this treasury
    uint256 public totalPrincipalLocked;

    // ═══════════════════════════════════════════════════════════
    // EVENTS
    // ═══════════════════════════════════════════════════════════

    event AgentStaked(
        address indexed agent,
        uint256 erc8004AgentId,
        uint256 wstETHAmount,
        address spendingWallet,
        uint256 timestamp
    );

    event YieldHarvested(
        address indexed agent,
        address indexed spendingWallet,
        uint256 yieldAmount,
        uint256 timestamp
    );

    event IdentityRegistryUpdated(address indexed oldRegistry, address indexed newRegistry);

    event ComplianceCheckFailed(address indexed agent, string reason);

    // ═══════════════════════════════════════════════════════════
    // ERRORS
    // ═══════════════════════════════════════════════════════════

    error NotCompliant(address agent);
    error NotRegisteredAgent(uint256 agentId);
    error AgentNotOwner(address agent, uint256 agentId);
    error ZeroAmount();
    error NoActivePosition(address agent);
    error NoYieldAvailable(address agent);
    error InvalidSpendingWallet();
    error OnlyOwner();
    error PositionAlreadyActive(address agent);

    // ═══════════════════════════════════════════════════════════
    // CONSTRUCTOR
    // ═══════════════════════════════════════════════════════════

    /**
     * @param _identityRegistry ERC-3643 Identity Registry address
     *        Set to address(0) to bypass compliance check in testing
     */
    constructor(address _identityRegistry) {
        owner = msg.sender;
        identityRegistry = _identityRegistry;
    }

    modifier onlyOwner() {
        if (msg.sender != owner) revert OnlyOwner();
        _;
    }

    // ═══════════════════════════════════════════════════════════
    // COMPLIANCE CHECKS
    // ═══════════════════════════════════════════════════════════

    /**
     * @notice Verify an agent is ERC-3643 compliant
     * @dev If identityRegistry is address(0), compliance check is bypassed (testing mode)
     */
    function _checkCompliance(address agent) internal view returns (bool) {
        if (identityRegistry == address(0)) return true; // bypass for testing
        return IIdentityRegistry(identityRegistry).isVerified(agent);
    }

    /**
     * @notice Verify an agent has a valid ERC-8004 onchain identity
     * @dev The agent calling this function must own the ERC-8004 token they claim
     */
    function _checkAgentIdentity(address agent, uint256 agentId) internal view returns (bool) {
        IAgentIdentityRegistry registry = IAgentIdentityRegistry(AGENT_REGISTRY);
        try registry.ownerOf(agentId) returns (address tokenOwner) {
            return tokenOwner == agent;
        } catch {
            return false;
        }
    }

    // ═══════════════════════════════════════════════════════════
    // CORE FUNCTIONS
    // ═══════════════════════════════════════════════════════════

    /**
     * @notice Stake wstETH into the compliance-gated yield treasury
     *
     * @dev Requirements:
     *   1. Agent must be verified in ERC-3643 identity registry (KYC/compliance)
     *   2. Agent must own their claimed ERC-8004 onchain identity token
     *   3. Agent must not already have an active position
     *   4. Amount must be > 0
     *
     * The wstETH is immediately deposited into Aave v3 to begin earning yield.
     * Principal is locked — it can never be directly withdrawn by the agent.
     * Only accrued yield flows to the agent's designated spending wallet.
     *
     * @param wstETHAmount Amount of wstETH to stake (in wei)
     * @param erc8004AgentId The agent's ERC-8004 identity token ID
     * @param spendingWallet Address where yield will be sent (Locus-controlled wallet)
     */
    function stake(
        uint256 wstETHAmount,
        uint256 erc8004AgentId,
        address spendingWallet
    ) external {
        if (wstETHAmount == 0) revert ZeroAmount();
        if (spendingWallet == address(0)) revert InvalidSpendingWallet();
        if (positions[msg.sender].active) revert PositionAlreadyActive(msg.sender);

        // ─── Compliance Gate 1: ERC-3643 identity verification ───
        if (!_checkCompliance(msg.sender)) {
            emit ComplianceCheckFailed(msg.sender, "ERC-3643: identity not verified");
            revert NotCompliant(msg.sender);
        }

        // ─── Compliance Gate 2: ERC-8004 agent identity ownership ───
        if (!_checkAgentIdentity(msg.sender, erc8004AgentId)) {
            emit ComplianceCheckFailed(msg.sender, "ERC-8004: agent identity not owned");
            revert AgentNotOwner(msg.sender, erc8004AgentId);
        }

        // ─── Transfer wstETH from agent to this contract ───
        IERC20(WSTETH).transferFrom(msg.sender, address(this), wstETHAmount);

        // ─── Approve Aave pool to spend wstETH ───
        IERC20(WSTETH).approve(AAVE_POOL, wstETHAmount);

        // ─── Snapshot aWSTETH balance before supply ───
        uint256 aWstETHBefore = IERC20(AWSTETH).balanceOf(address(this));

        // ─── Supply wstETH to Aave v3 — begin earning yield ───
        IAavePool(AAVE_POOL).supply(WSTETH, wstETHAmount, address(this), 0);

        // ─── Calculate aWSTETH shares received ───
        uint256 aWstETHAfter = IERC20(AWSTETH).balanceOf(address(this));
        uint256 sharesReceived = aWstETHAfter - aWstETHBefore;

        // ─── Record position ───
        positions[msg.sender] = AgentPosition({
            principalWstETH: wstETHAmount,
            aaveShares: sharesReceived,       // snapshot of principal-equivalent shares
            spendingWallet: spendingWallet,
            erc8004AgentId: erc8004AgentId,
            totalYieldHarvested: 0,
            stakedAt: block.timestamp,
            active: true
        });

        agents.push(msg.sender);
        totalPrincipalLocked += wstETHAmount;

        emit AgentStaked(msg.sender, erc8004AgentId, wstETHAmount, spendingWallet, block.timestamp);
    }

    /**
     * @notice Harvest accrued yield to the agent's spending wallet
     *
     * @dev Yield = current aWSTETH balance share value - principal shares value
     *
     * Aave's aTokens rebase automatically — the aWSTETH balance grows as interest accrues.
     * We track the initial shares (aaveShares), and any excess above that is pure yield.
     *
     * The yield (in wstETH) is withdrawn from Aave and sent to the agent's Locus wallet.
     * Principal shares remain in Aave, continuing to earn.
     */
    function harvestYield() external returns (uint256 yieldAmount) {
        AgentPosition storage pos = positions[msg.sender];
        if (!pos.active) revert NoActivePosition(msg.sender);

        // ─── Calculate yield ───
        // aWSTETH is a rebasing token — its balance grows as Aave accrues interest
        // Current balance in this contract's share of aWSTETH:
        uint256 currentTotalAWstETH = IERC20(AWSTETH).balanceOf(address(this));
        
        // The yield for this agent is proportional to their share of total aWSTETH
        // Simple approach: track per-agent aWSTETH balance directly
        // More accurate: current aWSTETH value > initial aaveShares → yield available
        if (currentTotalAWstETH <= pos.aaveShares) revert NoYieldAvailable(msg.sender);
        
        uint256 rawYield = currentTotalAWstETH - pos.aaveShares;
        
        // ─── Withdraw ONLY yield from Aave ───
        uint256 actualWithdrawn = IAavePool(AAVE_POOL).withdraw(WSTETH, rawYield, pos.spendingWallet);
        yieldAmount = actualWithdrawn;

        // ─── Update position ───
        pos.totalYieldHarvested += yieldAmount;
        // aaveShares stays the same — principal remains locked

        emit YieldHarvested(msg.sender, pos.spendingWallet, yieldAmount, block.timestamp);
    }

    // ═══════════════════════════════════════════════════════════
    // VIEW FUNCTIONS
    // ═══════════════════════════════════════════════════════════

    /**
     * @notice Get the current position details for an agent
     */
    function getPosition(address agent) external view returns (
        uint256 principalWstETH,
        uint256 currentAWstETH,
        uint256 estimatedYield,
        address spendingWallet,
        uint256 erc8004AgentId,
        uint256 totalYieldHarvested,
        uint256 stakedAt,
        bool active
    ) {
        AgentPosition storage pos = positions[agent];
        principalWstETH = pos.principalWstETH;
        spendingWallet = pos.spendingWallet;
        erc8004AgentId = pos.erc8004AgentId;
        totalYieldHarvested = pos.totalYieldHarvested;
        stakedAt = pos.stakedAt;
        active = pos.active;

        if (pos.active) {
            currentAWstETH = IERC20(AWSTETH).balanceOf(address(this));
            estimatedYield = currentAWstETH > pos.aaveShares 
                ? currentAWstETH - pos.aaveShares 
                : 0;
        }
    }

    /**
     * @notice Check if an agent is compliance-eligible to stake
     */
    function isEligible(address agent, uint256 erc8004AgentId) external view returns (
        bool erc3643Compliant,
        bool erc8004Valid,
        bool eligible
    ) {
        erc3643Compliant = _checkCompliance(agent);
        erc8004Valid = _checkAgentIdentity(agent, erc8004AgentId);
        eligible = erc3643Compliant && erc8004Valid;
    }

    /**
     * @notice Get all staked agents (for monitoring agent)
     */
    function getAgentCount() external view returns (uint256) {
        return agents.length;
    }

    /**
     * @notice Get total aWSTETH balance held by this treasury
     */
    function totalAaveBalance() external view returns (uint256) {
        return IERC20(AWSTETH).balanceOf(address(this));
    }

    // ═══════════════════════════════════════════════════════════
    // ADMIN
    // ═══════════════════════════════════════════════════════════

    /**
     * @notice Update ERC-3643 Identity Registry address
     * @dev Useful when deploying on networks where ERC-3643 infra varies
     */
    function setIdentityRegistry(address newRegistry) external onlyOwner {
        emit IdentityRegistryUpdated(identityRegistry, newRegistry);
        identityRegistry = newRegistry;
    }
}
